version: "3.7"

services:
    server:
        build: "."
        ports: [5596:8080]
        volumes:
            - type: bind
              source: ${music_directory}
              target: /music
        env_file:
            .env
